### ISSUE TITLE
Do you really need these print statements?

### ISSUE THREAD

**Issue by extsoft** [sashkalysenko/pbc-Lysenko#4]
https://github.com/sashkalysenko/pbc-Lysenko/blob/0b1778943c80401b9b2f749932babbed047762e7/tests/BDD_tests.py#L18

https://github.com/sashkalysenko/pbc-Lysenko/blob/0b1778943c80401b9b2f749932babbed047762e7/tests/BDD_tests.py#L31

**Comment by sashkalysenko** [comment]
Fixed in dac722a revision
